### ISSUE TITLE
Support sphinx warn option

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs-build#7]
Add some options to the YAML config to allow passing some options to sphinx-build.

Refs rtfd/readthedocs.org#1774

**Comment by leotrs** [comment]
What's the status of this feature? I'm having the same problem as in the referenced #1774.

**Comment by adamtheturtle** [comment]
This would be useful to me because sometimes there will be a warning on RTD and not Travis CI. For example, recently I found that a docs build required Docker to be running else there were warnings which resulted in malformed documentation. Docker was running on Travis CI. It would be useful for RTD to fail hard in this case, by using the `-W` option.

**Comment by stsewd** [comment]
This is already implemented, we moved this repo to the rtd code https://github.com/rtfd/readthedocs.org/pull/4482
